foldersTree = gFld("<b>Fly3D SDK 2.0</b>", "", "")
     insDoc(foldersTree, gLnk("Main Page", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("fly3D.h", "", "fly3_d_8h.html"))
       insDoc(aux1, gLnk("flyAI.h", "", "fly_a_i_8h.html"))
       insDoc(aux1, gLnk("flyAnimatedMesh.h", "", "fly_animated_mesh_8h.html"))
       insDoc(aux1, gLnk("flyArray.h", "", "fly_array_8h.html"))
       insDoc(aux1, gLnk("flyBaseObject.h", "", "fly_base_object_8h.html"))
       insDoc(aux1, gLnk("flyBezier.h", "", "fly_bezier_8h.html"))
       insDoc(aux1, gLnk("flyBoundBox.h", "", "fly_bound_box_8h.html"))
       insDoc(aux1, gLnk("flyBspNode.h", "", "fly_bsp_node_8h.html"))
       insDoc(aux1, gLnk("flyBspObject.h", "", "fly_bsp_object_8h.html"))
       insDoc(aux1, gLnk("flyConsole.h", "", "fly_console_8h.html"))
       insDoc(aux1, gLnk("flyDefine.h", "", "fly_define_8h.html"))
       insDoc(aux1, gLnk("flyDesc.h", "", "fly_desc_8h.html"))
       insDoc(aux1, gLnk("flyDirectX.h", "", "fly_direct_x_8h.html"))
       insDoc(aux1, gLnk("flyDll.h", "", "fly_dll_8h.html"))
       insDoc(aux1, gLnk("flyEngine.h", "", "fly_engine_8h.html"))
       insDoc(aux1, gLnk("flyFace.h", "", "fly_face_8h.html"))
       insDoc(aux1, gLnk("flyFile.h", "", "fly_file_8h.html"))
       insDoc(aux1, gLnk("flyFrustum.h", "", "fly_frustum_8h.html"))
       insDoc(aux1, gLnk("flyHashList.h", "", "fly_hash_list_8h.html"))
       insDoc(aux1, gLnk("flyInputMap.h", "", "fly_input_map_8h.html"))
       insDoc(aux1, gLnk("flyLight.h", "", "fly_light_8h.html"))
       insDoc(aux1, gLnk("flyLocalSystem.h", "", "fly_local_system_8h.html"))
       insDoc(aux1, gLnk("flyMath.h", "", "fly_math_8h.html"))
       insDoc(aux1, gLnk("flyMesh.h", "", "fly_mesh_8h.html"))
       insDoc(aux1, gLnk("flyOcTree.h", "", "fly_oc_tree_8h.html"))
       insDoc(aux1, gLnk("flyParticle.h", "", "fly_particle_8h.html"))
       insDoc(aux1, gLnk("flyPicture.h", "", "fly_picture_8h.html"))
       insDoc(aux1, gLnk("flyPolygon.h", "", "fly_polygon_8h.html"))
       insDoc(aux1, gLnk("flyRender.h", "", "fly_render_8h.html"))
       insDoc(aux1, gLnk("flyShader.h", "", "fly_shader_8h.html"))
       insDoc(aux1, gLnk("flySkeletonMesh.h", "", "fly_skeleton_mesh_8h.html"))
       insDoc(aux1, gLnk("flySound.h", "", "fly_sound_8h.html"))
       insDoc(aux1, gLnk("flyStaticMesh.h", "", "fly_static_mesh_8h.html"))
       insDoc(aux1, gLnk("flyString.h", "", "fly_string_8h.html"))
       insDoc(aux1, gLnk("flyTexCache.h", "", "fly_tex_cache_8h.html"))
       insDoc(aux1, gLnk("flyVideo.h", "", "fly_video_8h.html"))
aux1 = insFld(foldersTree, gFld("Compound List", "", "annotated.html"))
       insDoc(aux1, gLnk("flyAnimatedMesh", "", "classfly_animated_mesh.html"))
       insDoc(aux1, gLnk("flyArray", "", "classfly_array.html"))
       insDoc(aux1, gLnk("flyBaseObject", "", "classfly_base_object.html"))
       insDoc(aux1, gLnk("flyBezierCurve", "", "classfly_bezier_curve.html"))
       insDoc(aux1, gLnk("flyBezierPatch", "", "classfly_bezier_patch.html"))
       insDoc(aux1, gLnk("flyBoundBox", "", "classfly_bound_box.html"))
       insDoc(aux1, gLnk("flyBspNode", "", "classfly_bsp_node.html"))
       insDoc(aux1, gLnk("flyBspObject", "", "classfly_bsp_object.html"))
       insDoc(aux1, gLnk("flyClassDesc", "", "classfly_class_desc.html"))
       insDoc(aux1, gLnk("flyConsole", "", "classfly_console.html"))
       insDoc(aux1, gLnk("flyDirectx", "", "classfly_directx.html"))
       insDoc(aux1, gLnk("flyDll", "", "classfly_dll.html"))
       insDoc(aux1, gLnk("flyDllGroup", "", "classfly_dll_group.html"))
       insDoc(aux1, gLnk("flyEngine", "", "classfly_engine.html"))
       insDoc(aux1, gLnk("flyFace", "", "classfly_face.html"))
       insDoc(aux1, gLnk("flyFile", "", "classfly_file.html"))
       insDoc(aux1, gLnk("flyFrustum", "", "classfly_frustum.html"))
       insDoc(aux1, gLnk("flyHashList", "", "classfly_hash_list.html"))
       insDoc(aux1, gLnk("flyInputMap", "", "classfly_input_map.html"))
       insDoc(aux1, gLnk("flyLightMap", "", "classfly_light_map.html"))
       insDoc(aux1, gLnk("flyLightMapPic", "", "classfly_light_map_pic.html"))
       insDoc(aux1, gLnk("flyLightVertex", "", "classfly_light_vertex.html"))
       insDoc(aux1, gLnk("flyLocalSystem", "", "classfly_local_system.html"))
       insDoc(aux1, gLnk("flyMatrix", "", "classfly_matrix.html"))
       insDoc(aux1, gLnk("flyMesh", "", "classfly_mesh.html"))
       insDoc(aux1, gLnk("flyMPGames", "", "classfly_m_p_games.html"))
       insDoc(aux1, gLnk("flyMPMsg", "", "classfly_m_p_msg.html"))
       insDoc(aux1, gLnk("flyMPPlayerData", "", "classfly_m_p_player_data.html"))
       insDoc(aux1, gLnk("flyOcTree", "", "classfly_oc_tree.html"))
       insDoc(aux1, gLnk("flyOcTreeNode", "", "classfly_oc_tree_node.html"))
       insDoc(aux1, gLnk("flyParamDesc", "", "classfly_param_desc.html"))
       insDoc(aux1, gLnk("flyParticle", "", "classfly_particle.html"))
       insDoc(aux1, gLnk("flyPicture", "", "classfly_picture.html"))
       insDoc(aux1, gLnk("flyPlane", "", "classfly_plane.html"))
       insDoc(aux1, gLnk("flyPolygon", "", "classfly_polygon.html"))
       insDoc(aux1, gLnk("flyQuaternion", "", "classfly_quaternion.html"))
       insDoc(aux1, gLnk("flyRender", "", "classfly_render.html"))
       insDoc(aux1, gLnk("flyShader", "", "classfly_shader.html"))
       insDoc(aux1, gLnk("flyShaderFunc", "", "classfly_shader_func.html"))
       insDoc(aux1, gLnk("flyShaderPass", "", "classfly_shader_pass.html"))
       insDoc(aux1, gLnk("flySkeletonMesh", "", "classfly_skeleton_mesh.html"))
       insDoc(aux1, gLnk("flySound", "", "classfly_sound.html"))
       insDoc(aux1, gLnk("flyStateMachine", "", "classfly_state_machine.html"))
       insDoc(aux1, gLnk("flyStateMachineRule", "", "classfly_state_machine_rule.html"))
       insDoc(aux1, gLnk("flyStaticMesh", "", "classfly_static_mesh.html"))
       insDoc(aux1, gLnk("flyString", "", "classfly_string.html"))
       insDoc(aux1, gLnk("flyTexCache", "", "classfly_tex_cache.html"))
       insDoc(aux1, gLnk("flyTexInfo", "", "structfly_tex_info.html"))
       insDoc(aux1, gLnk("flyVector", "", "classfly_vector.html"))
       insDoc(aux1, gLnk("flyVertex", "", "classfly_vertex.html"))
       insDoc(aux1, gLnk("flyVideo", "", "classfly_video.html"))
aux1 = insFld(foldersTree, gFld("Class Hierarchy", "", "hierarchy.html"))
       insDoc(aux1, gLnk("flyArray", "", "classfly_array.html"))
  aux2 = insFld(aux1, gFld("flyBaseObject", "", "classfly_base_object.html"))
         insDoc(aux2, gLnk("flyBezierCurve", "", "classfly_bezier_curve.html"))
    aux3 = insFld(aux2, gFld("flyBspObject", "", "classfly_bsp_object.html"))
           insDoc(aux3, gLnk("flyStaticMesh", "", "classfly_static_mesh.html"))
    aux3 = insFld(aux2, gFld("flyMesh", "", "classfly_mesh.html"))
           insDoc(aux3, gLnk("flyAnimatedMesh", "", "classfly_animated_mesh.html"))
           insDoc(aux3, gLnk("flySkeletonMesh", "", "classfly_skeleton_mesh.html"))
         insDoc(aux2, gLnk("flyShader", "", "classfly_shader.html"))
         insDoc(aux2, gLnk("flySound", "", "classfly_sound.html"))
       insDoc(aux1, gLnk("flyBezierPatch", "", "classfly_bezier_patch.html"))
       insDoc(aux1, gLnk("flyBoundBox", "", "classfly_bound_box.html"))
       insDoc(aux1, gLnk("flyClassDesc", "", "classfly_class_desc.html"))
       insDoc(aux1, gLnk("flyConsole", "", "classfly_console.html"))
       insDoc(aux1, gLnk("flyDirectx", "", "classfly_directx.html"))
       insDoc(aux1, gLnk("flyDll", "", "classfly_dll.html"))
       insDoc(aux1, gLnk("flyDllGroup", "", "classfly_dll_group.html"))
       insDoc(aux1, gLnk("flyEngine", "", "classfly_engine.html"))
       insDoc(aux1, gLnk("flyFile", "", "classfly_file.html"))
       insDoc(aux1, gLnk("flyFrustum", "", "classfly_frustum.html"))
       insDoc(aux1, gLnk("flyHashList", "", "classfly_hash_list.html"))
       insDoc(aux1, gLnk("flyInputMap", "", "classfly_input_map.html"))
       insDoc(aux1, gLnk("flyLightMap", "", "classfly_light_map.html"))
       insDoc(aux1, gLnk("flyLightMapPic", "", "classfly_light_map_pic.html"))
       insDoc(aux1, gLnk("flyLightVertex", "", "classfly_light_vertex.html"))
  aux2 = insFld(aux1, gFld("flyLocalSystem", "", "classfly_local_system.html"))
         insDoc(aux2, gLnk("flyBspObject", "", "classfly_bsp_object.html"))
       insDoc(aux1, gLnk("flyMatrix", "", "classfly_matrix.html"))
       insDoc(aux1, gLnk("flyMPGames", "", "classfly_m_p_games.html"))
       insDoc(aux1, gLnk("flyMPMsg", "", "classfly_m_p_msg.html"))
       insDoc(aux1, gLnk("flyMPPlayerData", "", "classfly_m_p_player_data.html"))
       insDoc(aux1, gLnk("flyOcTree", "", "classfly_oc_tree.html"))
       insDoc(aux1, gLnk("flyOcTreeNode", "", "classfly_oc_tree_node.html"))
       insDoc(aux1, gLnk("flyParamDesc", "", "classfly_param_desc.html"))
  aux2 = insFld(aux1, gFld("flyParticle", "", "classfly_particle.html"))
         insDoc(aux2, gLnk("flyBspObject", "", "classfly_bsp_object.html"))
       insDoc(aux1, gLnk("flyPicture", "", "classfly_picture.html"))
  aux2 = insFld(aux1, gFld("flyPlane", "", "classfly_plane.html"))
         insDoc(aux2, gLnk("flyBspNode", "", "classfly_bsp_node.html"))
         insDoc(aux2, gLnk("flyFace", "", "classfly_face.html"))
         insDoc(aux2, gLnk("flyPolygon", "", "classfly_polygon.html"))
       insDoc(aux1, gLnk("flyRender", "", "classfly_render.html"))
       insDoc(aux1, gLnk("flyShaderFunc", "", "classfly_shader_func.html"))
       insDoc(aux1, gLnk("flyShaderPass", "", "classfly_shader_pass.html"))
       insDoc(aux1, gLnk("flyStateMachine", "", "classfly_state_machine.html"))
       insDoc(aux1, gLnk("flyStateMachineRule", "", "classfly_state_machine_rule.html"))
       insDoc(aux1, gLnk("flyString", "", "classfly_string.html"))
       insDoc(aux1, gLnk("flyTexCache", "", "classfly_tex_cache.html"))
       insDoc(aux1, gLnk("flyTexInfo", "", "structfly_tex_info.html"))
  aux2 = insFld(aux1, gFld("flyVector", "", "classfly_vector.html"))
         insDoc(aux2, gLnk("flyQuaternion", "", "classfly_quaternion.html"))
         insDoc(aux2, gLnk("flyVertex", "", "classfly_vertex.html"))
       insDoc(aux1, gLnk("flyVideo", "", "classfly_video.html"))
     insDoc(foldersTree, gLnk("Compound Members", "", "functions.html"))
     insDoc(foldersTree, gLnk("File Members", "", "globals.html"))
